version: "3.8"

services:
  env-vault:
    build: .
    ports:
      - "3000:3000"
    environment:
      DOPPLER_TOKEN_DEV: ${DOPPLER_TOKEN_DEV}
      ALLOWED_EMAILS: ${ALLOWED_EMAILS}
    env_file:
      - .env
